---
title: "deconvolution"
author: "Corinne Strawser"
date: "2025-05-19"
output: html_document
---

```{r load_ref_data}
# /igm/projects/240401_GSL-KM-3840_KC_flex/seurat/combine_with_gbmap/ohsv_pt_combine_with_gbmap.rmd
ref <- 
  readRDS("/igm/home/cnh008/ref/gbmap/2025_pub_and_mo32/merged_ohsv_gbmap_lognorm_harmony_with_manual_annotations.rds")

harmony <-
  list("pt22" = readRDS(paste0(output, "rdata/pt22_pre_and_post_merged_log_harmony.rds")),
       "pt18" = readRDS(paste0(output, "rdata/pt18_pre_and_post_merged_log_harmony.rds")))
```


```{r}
# make a reference umap
DimPlot(object = ref,
        group.by = c("dataset", "manual_annotation_v2"),
        shuffle = T,
        alpha = 0.8,
        label = T,
        label.box = T,
        repel = T) &
  guides(color = "none")
ggsave(paste0(fig,"deconvolution_v2/reference_annotation_v2_umaps.jpeg"),
       width = 12,
       height = 6)

# make a reference umap
ref$barcode <-
  rownames(ref@meta.data)
ref$barcode_sample <-
  substr(ref$barcode, 0, nchar(ref$barcode)-27)
ref$ohsv_timepoint <-
  ifelse(str_detect(pattern = "Post", string = ref$barcode_sample),
         "Post-oHSV","Pre-oHSV")
ref$barcode_sample <-
  ifelse(str_detect(pattern = "Patient", string = ref$barcode_sample),
         ref$barcode_sample,"GbMap")
ref$barcode_sample <-
  factor(ref$barcode_sample,
         levels = c("GbMap","Patient_18_Pre","Patient_18_Post","Patient_22_Post2"))
DimPlot(object = ref,
        group.by = c("manual_annotation_v2"),
        split.by = "barcode_sample",
        shuffle = T,
        alpha = 0.8,
        label = T,
        repel = T) &
  ggtitle("Annotation")
ggsave(paste0(fig,"deconvolution_v2/reference_annotation_v2_umaps_split_by_sample_timepoint.jpeg"),
       width = 24,
       height = 6)

# make a heatmap of cell type markers
Idents(ref) <- "manual_annotation_v2"
markers <-
  FindAllMarkers(object = ref,
                 only.pos = T,
                 min.pct = 0.2,
                 logfc.threshold = 0.25) %>%
  group_by(cluster) 
mks <- 
  markers %>%
  filter(p_val_adj <= 0.001)
write.csv(mks,
          paste0(de,"reference_annotation_v2_markers.csv"),
          row.names = F,
          quote = F)
top_markers <-
  markers %>%
  filter(!str_detect(gene, pattern = "LINC")) %>%
  arrange(desc(cluster)) %>%
  group_by(cluster) %>%
  slice_min(order_by = p_val_adj,
            n = 20,
            with_ties = T) %>%
  slice_max(order_by = avg_log2FC,
            n = 5,
            with_ties = F) %>%
  pull(gene)
ref <-
  ScaleData(object = ref,
            features = top_markers)
DoHeatmap(object = subset(ref,
                          downsample = 500),
          features = top_markers,
          size = 4) &
  guides(color = "none")
ggsave(paste0(fig,"deconvolution_v2/reference_annotation_v2_marker_heatmap.jpeg"),
       width = 10,
       height = 14)

# make a dot plot of cell type markers
top_markers <-
  markers %>%
  filter(!str_detect(gene, pattern = "LINC")) %>%
  group_by(cluster) %>%
  slice_min(order_by = p_val_adj,
            n = 20,
            with_ties = T) %>%
  slice_max(order_by = avg_log2FC,
            n = 3,
            with_ties = F) %>%
  pull(gene) %>%
  unique()
ref@meta.data$EGFR <- NULL
DotPlot(object = ref,
        group.by = "manual_annotation_v2",
        features = top_markers) &
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1, 
                                   vjust = 1)) &
  scale_color_continuous(type = "viridis")
ggsave(paste0(fig,"deconvolution_v2/reference_annotation_v2_marker_dotplot.jpeg"),
       width = 20,
       height = 7)
# vertical dotplot
DotPlot(object = ref,
        group.by = "manual_annotation_v2",
        features = top_markers) &
  coord_flip() &
  scale_color_continuous(type = "viridis") &
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1, 
                                   vjust = 1),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title.position = "top",
        legend.title = element_text(hjust = 0.5),
        legend.justification = "center")
ggsave(paste0(fig,"deconvolution_v2/reference_annotation_v2_marker_dotplot_vertical.jpeg"),
       width = 6,
       height = 11)
```

```{r spacexr_manual_annotation}
# Create the Reference object
spacexr_reference <-
    spacexr::Reference(GetAssayData(ref, 
                                    layer = "counts"),
                       as.factor(ref$manual_annotation_v2))
remove(ref)

sample_coords <-
  list("pt22" = rbind(GetTissueCoordinates(harmony[["pt22"]], 
                                           image = "oHSV_d0"),
                      GetTissueCoordinates(harmony[["pt22"]], 
                                           image = "oHSV_d51"),
                      GetTissueCoordinates(harmony[["pt22"]], 
                                           image = "oHSV_d119")) %>%
         rename(x = imagerow,
                y = imagecol),
       "pt18" = rbind(GetTissueCoordinates(harmony[["pt18"]], 
                                           image = "oHSV_d0"),
                      GetTissueCoordinates(harmony[["pt18"]], 
                                           image = "oHSV_d122")) %>%
         rename(x = imagerow,
                y = imagecol))

for (pt_name in names(harmony)){
  coords <- 
    sample_coords[[pt_name]]
  my_data <- 
    spacexr::SpatialRNA(coords,
                        GetAssayData(harmony[[pt_name]], 
                                     layer = "counts",
                                     assay = "Spatial"))
  rctd_obj <- 
    spacexr::create.RCTD(my_data, 
                         spacexr_reference,
                         CELL_MIN_INSTANCE = 1,
                         fc_cutoff = 0.2,
                         UMI_min = 10)
  
  rctd_out <- 
    spacexr::run.RCTD(rctd_obj, 
                      doublet_mode = "full")
  
  saveRDS(rctd_out, 
          paste0(rdata, pt_name, "_pre_and_post_merged_log_harmony_rctd_out_manual_annotation_v2.rds"))
  
  norm_weights <- 
    spacexr::normalize_weights(rctd_out@results$weights)
  
  saveRDS(norm_weights, 
          paste0(rdata, pt_name, "_pre_and_post_merged_log_harmony_rctd_out_manual_annotation_v2_norm_weights.rds"))
  
  data_manual <- 
    AddMetaData(harmony[[pt_name]], 
                norm_weights)
  
  data_manual@meta.data[is.na(data_manual@meta.data)] <- 0
  
  saveRDS(data_manual, 
          paste0(rdata, pt_name, "_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds"))
}
```

```{r}
# read deconvoluted data back in
harmony <-
  list("pt22" = readRDS(paste0(output, "rdata/pt22_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds")),
       "pt18" = readRDS(paste0(output, "rdata/pt18_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds")))

ref <- 
  readRDS("/igm/home/cnh008/ref/gbmap/2025_pub_and_mo32/merged_ohsv_gbmap_lognorm_harmony_with_manual_annotations.rds")
Idents(ref) <- "manual_annotation_v2"
ref <-
  subset(ref,
         downsample = 1000)
```

```{r}
# add meta data about sample
for (pt_name in names(harmony)){
  pt <-
    harmony[[pt_name]]
  pt[["patient"]] <-
    str_split_fixed(string = pt$orig.ident,
                    pattern = "_",
                    n = 2)[,1]
  pt[["oHSV"]] <-
    str_split_fixed(string = pt$orig.ident,
                    pattern = "_",
                    n = 2)[,2]
  pt$oHSV <- 
    ifelse(pt$oHSV == "pre",
           "pre-oHSV", "post-oHSV")
  pt[["timepoint"]] <-
    str_split_fixed(string = pt$orig.ident,
                    pattern = "_",
                    n = 2)[,2] %>%
    gsub(pattern = "pre",
         replacement = "oHSV_d0", .) %>%
    gsub(pattern = "post1",
         replacement = "oHSV_d51", .) %>%
    gsub(pattern = "post2",
         replacement = "oHSV_d119", .) %>%
    gsub(pattern = "post",
         replacement = "oHSV_d122", .)
  harmony[[pt_name]] <- pt
  saveRDS(pt, 
          paste0(rdata, pt_name, "_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds"))  
}
```

```{r}
celltypes <-
  unique(ref$manual_annotation_v2)

celltypes <-
  c("Neoplastic","TAM","Oligodendrocyte","Endothelial","DC",
    "Astrocyte","Mural cell","Monocytes","T cell","RG","Plasma B",
    "NK","Neuron","Mast","pDC","B cell","OPC","Treg")
```

```{r}
# make some plots for Patient 18
for (pt_name in "pt18"){
  stats <- data.frame()
  for (celltype in celltypes){
    pre <-
      harmony[[pt_name]]@meta.data[harmony[[pt_name]]@meta.data$oHSV == "pre-oHSV", celltype]
    post <-
      harmony[[pt_name]]@meta.data[harmony[[pt_name]]@meta.data$oHSV == "post-oHSV", celltype]
    pval <-
      wilcox.test(x = pre,
                  y = post)
    stats <- 
      rbind(stats, c(celltype, mean(pre), mean(post), pval$p.value))
  }
  colnames(stats) <-
    c("cell_type","pre_mean", "post_mean", "pval")
  stats$FDR <-
    p.adjust(stats$pval, "BH")
  write.csv(stats,
            paste0(fig, "deconvolution_v2/",pt_name,"_pre_vs_post_deconvolution_stats.csv"),
            row.names = F,
            quote = F) 
  for (celltype in celltypes){
    celltype_stats <-
      stats %>%
      filter(cell_type == celltype) %>%
      pivot_longer(cols = c("pre_mean", "post_mean"),
                   names_to = "timepoint",
                   values_to = "mean") %>%
      mutate(mean = as.numeric(mean) %>%
               round(digits = 3)) %>%
      rename({{celltype}} := "cell_type")
    VlnPlot(object = harmony[[pt_name]],
            features = celltype,
            cols = c("#476ba5","#D66363"),
            group.by = "timepoint",
            alpha = 0.2) &
      stat_summary(fun = "mean",
                   geom = "crossbar",
                   width = 0.3,
                   position = position_dodge(width = 0.9),
                   linewidth = 0.5,
                   show.legend = F) &
      ggtitle(paste0(gsub(pattern = "pt",
                          replacement = "Patient ",
                          x = pt_name), 
                     "\n",
                     gsub(pattern = "_",
                          replacement = " ",
                          x = celltype))) &
      ylab("Normalized Deconvolution Weight") &
      xlab(NULL) &
      guides(fill = "none") &
      labs(caption = paste("FDR =", stats[stats$cell_type == celltype, "FDR"])) &
      theme(axis.text.x = element_text(angle = 0,
                                       hjust = 0.5),
            plot.caption = element_text(hjust = 0.5),
            plot.title = element_text(size = 14)) 
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_vlnplot.jpeg"),
           width = 7,
           height = 6)
    min <-
      round(min(harmony[[pt_name]][[celltype]]), 2) + 0.01
    max <-
      round(max(harmony[[pt_name]][[celltype]]), 2) - 0.01
    spatialplots <- list()
    for (image in names(harmony[[pt_name]]@images)){
      pt.size <- 
        ifelse(test = pt_name == "pt22" & image == "oHSV_d0",
               yes = 1.6, no = 3)
      spatialplots[[image]] <-
        SpatialFeaturePlot(object = subset(harmony[[pt_name]],
                                           timepoint == image),
                           features = celltype,
                           min.cutoff = min,
                           max.cutoff = max,
                           images = image,
                           pt.size.factor = ifelse(pt_name == "pt22", pt.size, 1.6)) &
        labs(title = paste0(gsub("pt", "Patient ", pt_name),"\n",image)) &
        scale_fill_gradientn(colours = rainbow,
                             limits = c(0, max),
                             na.value = rainbow[9],
                             name = paste0(celltype, "\nMean Deconvolution\nWeight"),
                             oob = scales::squish) &
        theme(plot.title = element_text(hjust = 0.5))
    }
    wrap_plots(spatialplots) +
      plot_layout(guides = "collect") & 
      theme(legend.position = "right", 
            legend.direction = "vertical")
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_spatialplot.jpeg"),
           width = 9,
           height = 4.5)
  }
}

# make better violin plots
for (pt_name in "pt18"){
  for (celltype in celltypes){
    harmony[[pt_name]]@meta.data[,c("timepoint",celltype)] %>%
      rename("cell_type" := {{celltype}}) %>% 
      ggplot(aes(x = timepoint, 
                 y = cell_type,
                 fill = timepoint,
                 color = timepoint)) &
      geom_point(position = position_jitterdodge(),
                 alpha = 0.1) &
      geom_violin(alpha = 0.3) &
      stat_summary(fun = "mean",
                   geom = "crossbar",
                   width = 0.3,
                   position = position_dodge(width = 0.4),
                   linewidth = 0.2,
                   linetype = 1,
                   show.legend = F,
                   color = "black") &
      stat_summary(fun = mean,
                   geom = "text",
                   aes(label = after_stat(round(y, 3))),
                   vjust = -0.7,      # move label above the bar
                   color = "black") &
      ggtitle(paste0(gsub(pattern = "pt",
                          replacement = "Patient ",
                          x = pt_name), 
                     "\n",
                     gsub(pattern = "_",
                          replacement = " ",
                          x = celltype))) &
      ylab("Normalized Deconvolution Weight") &
      xlab(NULL) &
      guides(fill = "none",
             color = "none")  &
      stat_compare_means(label = "p.signif",
                         label.x.npc = "center",
                         size = 5) &
      scale_fill_manual(values = c("oHSV_d0" = "#476ba5",
                                   "oHSV_d122" = "#D66363")) &
      scale_color_manual(values = c("oHSV_d0" = "#476ba5",
                                   "oHSV_d122" = "#D66363")) &
      theme_bw() &
      theme(axis.text.x = element_text(angle = 0,
                                       hjust = 0.5),
            plot.caption = element_text(hjust = 0.5),
            plot.title = element_text(hjust = 0.5,
                                      size = 12,
                                      face = "bold"))
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_vlnplot_v3.jpeg"),
           width = 3.5,
           height = 5)
  }
}

for (pt_name in "pt18"){
  # calculate cell type correlation in spots in pre- and post-oHSV samples
  # pre-oHSV
  pre <-
    subset(harmony[[pt_name]], timepoint == "oHSV_d0")
  pre_cell_data <-
    pre@meta.data[,celltypes]
  
  pre_cell_cor <-  
    cor(pre_cell_data, 
        method = "spearman")
  
  pre_cell_cor_df <-
    pre_cell_cor %>%
    as.data.frame() %>% 
    rownames_to_column("celltype1") %>%
    mutate(celltype1 = as.factor(celltype1)) %>%
    pivot_longer(cols = -celltype1,
                 values_to = "cor",
                 names_to = "celltype2") %>%
    as.data.frame() %>%
    mutate(timepoint = "oHSV_d0")
  
  # Post-oHSV
  post <-
    subset(harmony[[pt_name]], timepoint == "oHSV_d122")
  post_cell_data <-
    post@meta.data[,celltypes]
  
  post_cell_cor <-  
    cor(post_cell_data, 
        method = "spearman")
  
  post_cell_cor_df <-
    post_cell_cor %>%
    as.data.frame() %>% 
    rownames_to_column("celltype1") %>%
    mutate(celltype1 = as.factor(celltype1)) %>%
    pivot_longer(cols = -celltype1,
                 values_to = "cor",
                 names_to = "celltype2") %>%
    as.data.frame() %>%
    mutate(timepoint = "oHSV_d122")
  
  cors <-
    rbind(pre_cell_cor_df,
          post_cell_cor_df)
  cors %>%
    filter(celltype1 != "TAM-BDM.1" &
             celltype2 != "TAM-BDM.1") %>%
    ggplot(aes(x = celltype1,
               y = celltype2)) +
    geom_tile(aes(fill = cor)) +
    scale_fill_gradient2(low = "blue",
                          high = "red",
                          mid = "white",
                          midpoint = 0,
                          name = "Cell Type Correlation",
                          limits = c(-1,1)) +
    labs(x = NULL,
         y = NULL) +
    facet_wrap(~timepoint) +
    theme_bw() +
    scale_x_discrete(expand = c(0,0)) +
    scale_y_discrete(expand = c(0,0)) +
    theme(text = element_text(size = 12),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1,
                                     vjust = 1),
          strip.background = element_rect(fill = "white"))
  ggsave(filename = paste0(fig, "deconvolution_v2/", pt_name, "_pre_vs_post_tumor_cell_cor.jpeg"),
         width = 12,
         height = 6)
}
```


```{r}
# make some plots for Patient 22
for (pt_name in "pt22"){
  stats <- data.frame()
  for (celltype in celltypes){
    ct <-
      harmony[[pt_name]]@meta.data[,c("timepoint",celltype)]
    colnames(ct) <- c("timepoint", "celltype")
    anova <-
      aov(data = ct,
          formula = celltype ~ timepoint)
    tukey <-
      TukeyHSD(anova)$timepoint %>%
      as.data.frame() %>%
      rownames_to_column(var = "comparison") %>%
      mutate("celltype" = celltype,
             "pre_mean" = mean(ct[ct$timepoint == "oHSV_d0","celltype"]),
             "post1_mean" = mean(ct[ct$timepoint == "oHSV_d51","celltype"]),
             "post2_mean" = mean(ct[ct$timepoint == "oHSV_d119","celltype"]))
    stats <- 
      rbind(stats, tukey)
  }
  stats$FDR <-
    p.adjust(stats[["p adj"]], "BH")
  write.csv(stats,
            paste0(fig, "deconvolution_v2/",pt_name,"_pre_vs_post_deconvolution_stats.csv"),
            row.names = F,
            quote = F) 
  for (celltype in celltypes){
    VlnPlot(object = harmony[[pt_name]],
            features = celltype,
            cols = c("#476ba5","#DB9C9C","#D66363"),
            group.by = "timepoint",
            alpha = 0.2) &
      stat_summary(fun = "mean",
                   geom = "crossbar",
                   width = 0.3,
                   position = position_dodge(width = 0.9),
                   linewidth = 0.5,
                   show.legend = F) &
      ggtitle(paste0(gsub(pattern = "pt",
                          replacement = "Patient ",
                          x = pt_name), 
                     "\n",
                     gsub(pattern = "_",
                          replacement = " ",
                          x = celltype))) &
      ylab("Normalized Deconvolution Weight") &
      xlab(NULL) &
      guides(fill = "none") &
      theme(axis.text.x = element_text(angle = 0,
                                       hjust = 0.5),
            plot.caption = element_text(hjust = 0.5),
            plot.title = element_text(size = 14)) 
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_vlnplot.jpeg"),
           width = 7,
           height = 6)
    min <-
      round(min(harmony[[pt_name]][[celltype]]), 2) + 0.01
    max <-
      round(max(harmony[[pt_name]][[celltype]]), 2) - 0.01
    spatialplots <- list()
    for (image in names(harmony[[pt_name]]@images)){
      pt.size <- 
        ifelse(test = pt_name == "pt22" & image == "oHSV_d0",
               yes = 1.6, no = 3)
      spatialplots[[image]] <-
        SpatialFeaturePlot(object = subset(harmony[[pt_name]],
                                           timepoint == image),
                           features = celltype,
                           min.cutoff = min,
                           max.cutoff = max,
                           images = image,
                           pt.size.factor = ifelse(pt_name == "pt22", pt.size, 1.6)) &
        labs(title = paste0(gsub("pt", "Patient ", pt_name),"\n",image)) &
        scale_fill_gradientn(colours = rainbow,
                             limits = c(0, max),
                             na.value = rainbow[9],
                             paste0(celltype, "\nMean Deconvolution\nWeight"),
                             oob = scales::squish) &
        theme(plot.title = element_text(hjust = 0.5))
    }
    wrap_plots(spatialplots) +
      plot_layout(guides = "collect") & 
      theme(legend.position = "right", 
            legend.direction = "vertical")
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_spatialplot.jpeg"),
           width = 12,
           height = 4.5)
  }
}

# make better violin plots
for (pt_name in "pt22"){
  my_comparisons <- 
    list( c("oHSV_d0", "oHSV_d51"), c("oHSV_d0", "oHSV_d119"), c("oHSV_d51", "oHSV_d119") )
  for (celltype in celltypes){
    harmony[[pt_name]]@meta.data[,c("timepoint",celltype)] %>%
      rename("cell_type" := {{celltype}}) %>% 
      ggplot(aes(x = timepoint, 
                 y = cell_type,
                 fill = timepoint,
                 color = timepoint)) &
      geom_point(position = position_jitterdodge(),
                 alpha = 0.1) &
      geom_violin(alpha = 0.3) &
      stat_summary(fun = "mean",
                   geom = "crossbar",
                   width = 0.3,
                   position = position_dodge(width = 0.4),
                   linewidth = 0.2,
                   linetype = 1,
                   show.legend = F,
                   color = "black") &
      stat_summary(fun = mean,
                   geom = "text",
                   aes(label = after_stat(round(y, 3))),
                   vjust = -0.7,      # move label above the bar
                   color = "black") &
      ggtitle(paste0(gsub(pattern = "pt",
                          replacement = "Patient ",
                          x = pt_name), 
                     "\n",
                     gsub(pattern = "_",
                          replacement = " ",
                          x = celltype))) &
      ylab("Normalized Deconvolution Weight") &
      xlab(NULL) &
      guides(fill = "none",
             color = "none")  &
      stat_compare_means(comparisons = my_comparisons,
                         p.adjust.methods = "bonferroni",
                         label = "p.signif",
                         label.x.npc = "center",
                         size = 5) &
      scale_fill_manual(values = c("oHSV_d0" = "#476ba5",
                                   "oHSV_d51" = "#D66363",
                                   "oHSV_d119" = "#05AB6F")) &
      scale_color_manual(values = c("oHSV_d0" = "#476ba5",
                                   "oHSV_d51" = "#D66363",
                                   "oHSV_d119" = "#05AB6F")) &
      theme_bw() &
      theme(axis.text.x = element_text(angle = 0,
                                       hjust = 0.5),
            plot.caption = element_text(hjust = 0.5),
            plot.title = element_text(hjust = 0.5,
                                      size = 12,
                                      face = "bold"))
    ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_", celltype,"_deconvolution_weight_vlnplot_v3.jpeg"),
           width = 4.5,
           height = 5.5)
  }
}

for (pt_name in "pt22"){
  # calculate cell type correlation in spots in pre- and post-oHSV samples
  # pre-oHSV
  pre <-
    subset(harmony[[pt_name]], timepoint == "oHSV_d0")
  pre_cell_data <-
    pre@meta.data[,celltypes]
  
  pre_cell_cor <-  
    cor(pre_cell_data, 
        method = "spearman")
  
  pre_cell_cor_df <-
    pre_cell_cor %>%
    as.data.frame() %>% 
    rownames_to_column("celltype1") %>%
    mutate(celltype1 = as.factor(celltype1)) %>%
    pivot_longer(cols = -celltype1,
                 values_to = "cor",
                 names_to = "celltype2") %>%
    as.data.frame() %>%
    mutate(timepoint = "oHSV_d0")
  
  # Post-oHSV
  post1 <-
    subset(harmony[[pt_name]], timepoint == "oHSV_d51")
  post1_cell_data <-
    post1@meta.data[,celltypes]
  
  post1_cell_cor <-  
    cor(post1_cell_data, 
        method = "spearman")
  
  post1_cell_cor_df <-
    post1_cell_cor %>%
    as.data.frame() %>% 
    rownames_to_column("celltype1") %>%
    mutate(celltype1 = as.factor(celltype1)) %>%
    pivot_longer(cols = -celltype1,
                 values_to = "cor",
                 names_to = "celltype2") %>%
    as.data.frame() %>%
    mutate(timepoint = "oHSV_d51")
  
  # Post-oHSV
  post2 <-
    subset(harmony[[pt_name]], timepoint == "oHSV_d119")
  post2_cell_data <-
    post2@meta.data[,celltypes]
  
  post2_cell_cor <-  
    cor(post2_cell_data, 
        method = "spearman")
  
  post2_cell_cor_df <-
    post2_cell_cor %>%
    as.data.frame() %>% 
    rownames_to_column("celltype1") %>%
    mutate(celltype1 = as.factor(celltype1)) %>%
    pivot_longer(cols = -celltype1,
                 values_to = "cor",
                 names_to = "celltype2") %>%
    as.data.frame() %>%
    mutate(timepoint = "oHSV_d119")
  
  cors <-
    rbind(pre_cell_cor_df,
          post1_cell_cor_df,
          post2_cell_cor_df)
  cors$timepoint <-
    factor(cors$timepoint,
           levels = c("oHSV_d0","oHSV_d51","oHSV_d119"))
  cors %>%
    filter(celltype1 != "TAM-BDM.1" &
             celltype2 != "TAM-BDM.1") %>%
    ggplot(aes(x = celltype1,
               y = celltype2)) +
    geom_tile(aes(fill = cor)) +
    scale_fill_gradient2(low = "blue",
                          high = "red",
                          mid = "white",
                          midpoint = 0,
                          name = "Cell Type Correlation",
                          limits = c(-1,1)) +
    labs(x = NULL,
         y = NULL) +
    facet_wrap(~timepoint) +
    theme_bw() +
    scale_x_discrete(expand = c(0,0)) +
    scale_y_discrete(expand = c(0,0)) +
    theme(text = element_text(size = 12),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1,
                                     vjust = 1),
          strip.background = element_rect(fill = "white"))
  ggsave(filename = paste0(fig, "deconvolution_v2/", pt_name, "_pre_vs_post_tumor_cell_cor.jpeg"),
         width = 18,
         height = 6)
}
```

```{r}
for (pt_name in names(harmony)){
  means <-
    harmony[[pt_name]]@meta.data %>%
    dplyr::select(c(timepoint,!!celltypes)) %>%
    group_by(timepoint) %>% 
    summarise_at(vars(celltypes), mean) %>%
    pivot_longer(cols = celltypes,
                 values_to = "mean",
                 names_to = "celltype") %>%
    mutate(timepoint = factor(timepoint,
                              levels = c("oHSV_d0","oHSV_d51",
                                         "oHSV_d119","oHSV_d122")))
  means %>%
    ggplot(aes(x = timepoint,
               y = mean,
               color = celltype)) +
    facet_wrap(~celltype) +
    geom_line(aes(group = celltype)) +
    geom_point() +
    scale_color_manual(values = colors) +
    guides(color = "none") +
    theme_bw() +
    xlab("Timepoint") +
    ylab("Mean Normalized Deconvolution Score") +
    theme(strip.background = element_rect(fill = "white"),
          axis.text.x = element_text(angle = 45,
                                     vjust = 1,
                                     hjust = 1))
  ggsave(filename = paste0(fig, "deconvolution_v2/", pt_name, "_pre_vs_post_deconvolution_v2_weights_lineplot.jpeg"),
         width = 10,
         height = 10)
}
```

```{r}
for (pt_name in names(harmony)){
  # calculate cell type correlation in spots in pre- and post-oHSV samples
  correlations <- data.frame()
  for (tp in unique(harmony[[pt_name]]$timepoint)){
    sub <-
      subset(harmony[[pt_name]], 
             timepoint == tp)
    cor <- 
      cor(sub@meta.data[,celltypes],
          method = "spearman") %>%
      as.data.frame() %>% 
      rownames_to_column("celltype1") %>%
      mutate(celltype1 = as.factor(celltype1)) %>%
      pivot_longer(cols = -celltype1,
                   values_to = "cor",
                   names_to = "celltype2") %>%
      as.data.frame() %>%
      mutate(timepoint = tp)
    correlations <-
      rbind(correlations,
            cor)
  }
  correlations$timepoint <-
    factor(correlations$timepoint,
           levels = c("oHSV_d0","oHSV_d51","oHSV_d119","oHSV_d122"))
  correlations %>%
    filter(celltype1 == "Neoplastic",
           celltype2 != "Neoplastic") %>%
    ggplot(aes(y = celltype2,
               x = timepoint)) +
    geom_tile(aes(fill = cor)) +
    scale_fill_gradient2(low = "blue",
                          high = "red",
                          mid = "white",
                          midpoint = 0,
                          name = "Correlation with\nNeoplastic Cells",
                          limits = c(-1,1)) +
    labs(x = NULL,
         y = NULL) +
    theme_bw() +
    scale_x_discrete(expand = c(0,0)) +
    scale_y_discrete(expand = c(0,0)) +
    theme(text = element_text(size = 12))
  ggsave(filename = paste0(fig, "deconvolution_v2/", pt_name, "_pre_vs_post_tumor_cell_cor.jpeg"),
         width = ifelse(pt_name == "pt22", 7, 5),
         height = 6)
}
```

```{r}
# read in deconvoluted data
harmony <-
  list("pt22" = readRDS(paste0(output, "rdata/pt22_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds")),
       "pt18" = readRDS(paste0(output, "rdata/pt18_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds")))
```

```{r}
for (pt_name in names(harmony)){
  pt <- 
    harmony[[pt_name]]
  for (ct in celltypes){
    pt[[paste(ct, "present")]] <-
      ifelse(pt[[ct]] >= median(unlist(pt[[ct]]), na.rm = T),
             TRUE, FALSE)
  }
  harmony[[pt_name]] <- pt
  saveRDS(pt, 
          paste0(rdata, pt_name, "_pre_and_post_merged_log_harmony_deconvoluted_cell_manual_annotation_v2.rds"))
}
```

```{r}
for (pt_name in names(harmony)){
  df <- harmony[[pt_name]]@meta.data[,7:24]
  df$anno <- NA
  for (i in 1:nrow(df)){
    sm <- df[i,1:18] %>%
      unlist() %>%
      sort()
    ct <- names(sm[length(sm)])
    df[i,"anno"] <- ct
  }
  harmony[[pt_name]]$deconvolution_cell_type <-
    df$anno
}

cell_type_colors <-
  colors[1:18]
names(cell_type_colors) <-
  colnames(df[1:18])

for (pt_name in names(harmony)){
  spatialplots <- list()
  for (image in names(harmony[[pt_name]]@images)){
    pt.size <- 
      ifelse(test = pt_name == "pt22" & image == "oHSV_d0",
             yes = 1.6, no = 3)
    spatialplots[[image]] <-
      SpatialDimPlot(object = subset(harmony[[pt_name]],
                                         timepoint == image),
                         group.by = "deconvolution_cell_type",
                         cols = cell_type_colors,
                         pt.size.factor = ifelse(pt_name == "pt22", pt.size, 1.6)) &
      scale_fill_manual(name = "Deconvolution\nCell Type",
                        values = cell_type_colors) &
      guides(fill = guide_legend(override.aes = list(size = 3, alpha = 1))) &
      labs(title = paste0(gsub("pt", "Patient ", pt_name),"\n",image)) &
      theme(plot.title = element_text(hjust = 0.5))
  }
  wrap_plots(spatialplots) +
    plot_layout(guides = "collect") & 
    theme(legend.position = "right", 
          legend.direction = "vertical")
  ggsave(paste0(fig,"deconvolution_v2/",pt_name,"_deconvolution_cell_type_spatialplot.jpeg"),
         width = ifelse(pt_name == "pt22", 12, 9),
         height = 4.5)
}
```

